import { describe, it, expect, afterEach, vi } from 'vitest';
import { EdgeBlockedError } from '@chrischall/mcp-utils';
import { fetchApiVersion, HoneyBookClient } from '../src/client.js';
import type { CapturedSession } from '../src/types.js';

// chrischall/mcp-host#1015: a CDN/WAF refusal page in front of
// api.honeybook.com never reached HoneyBook, so the session was never judged.
// It must read as an edge block — not "auth expired, re-run use_magic_link" and
// not "Rate limited" — and that needs the body, which the client used to drop
// on a 401 or 429.

const MOCK_SESSION: CapturedSession = {
  portalOrigin: 'https://vendor.hbportal.co',
  companyName: 'Vendor Co',
  authToken: 'tok_43',
  userId: 'uid_24',
  capturedAt: 1745000000000,
};

const CLOUDFRONT_BLOCK = `<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: 3xAmPlE-rEqUeSt-iD==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>`;

const CLOUDFLARE_CHALLENGE = `<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head>
<body><div class="main-wrapper" role="main"><div class="main-content">
<noscript><div class="h2"><span id="challenge-error-text">Enable JavaScript and cookies to continue</span></div></noscript>
</div></div><script>(function(){window._cf_chl_opt={cvId: '3',cZone: "api.honeybook.com",cType: 'managed'};
var cpo = document.createElement('script');cpo.src = '/cdn-cgi/challenge-platform/h/g/orchestrate/chl_page/v1?ray=8f0e1d2c3b4a5968';
document.getElementsByTagName('head')[0].appendChild(cpo);}());</script></body></html>`;

function htmlResponse(body: string, status: number, headers: Record<string, string> = {}): Response {
  return new Response(body, { status, headers: { 'content-type': 'text/html', ...headers } });
}

afterEach(() => {
  vi.restoreAllMocks();
  vi.useRealTimers();
});

describe('edge-block pages from api.honeybook.com', () => {
  it('reports a 401 CloudFront block page as EdgeBlockedError, not auth expired', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValue(htmlResponse(CLOUDFRONT_BLOCK, 401));
    const client = new HoneyBookClient(MOCK_SESSION, 2578);
    const err = await client.request('GET', '/api/v2/users/uid_24').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect((err as EdgeBlockedError).vendor).toBe('CloudFront');
    expect((err as EdgeBlockedError).status).toBe(401);
    expect((err as Error).message).not.toMatch(/auth expired|use_magic_link/);
  });

  it('reports a 429 Cloudflare challenge as EdgeBlockedError without retrying', async () => {
    const fetchSpy = vi
      .spyOn(globalThis, 'fetch')
      .mockResolvedValue(htmlResponse(CLOUDFLARE_CHALLENGE, 429, { 'cf-mitigated': 'challenge' }));
    const client = new HoneyBookClient(MOCK_SESSION, 2578);
    const err = await client.request('GET', '/api/v2/users/uid_24').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
    expect((err as EdgeBlockedError).vendor).toBe('Cloudflare');
    expect((err as Error).message).not.toMatch(/Rate limited/);
    expect(fetchSpy).toHaveBeenCalledTimes(1);
  });

  it('reports a 403 Cloudflare challenge as EdgeBlockedError, not a generic HoneyBook error', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValue(
      htmlResponse(CLOUDFLARE_CHALLENGE, 403, { 'cf-mitigated': 'challenge' })
    );
    const client = new HoneyBookClient(MOCK_SESSION, 2578);
    const err = await client.request('GET', '/api/v2/users/uid_24').catch((e: unknown) => e);
    expect(err).toBeInstanceOf(EdgeBlockedError);
  });

  it('reports a blocked /api/gon as EdgeBlockedError, not an unparseable version', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValue(htmlResponse(CLOUDFRONT_BLOCK, 403));
    await expect(fetchApiVersion()).rejects.toBeInstanceOf(EdgeBlockedError);
  });

  it('control: a genuine JSON 401 still reads as an expired session', async () => {
    vi.spyOn(globalThis, 'fetch').mockResolvedValue(
      new Response('{"error":true,"error_type":"HBAuthenticationError"}', {
        status: 401,
        headers: { 'content-type': 'application/json' },
      })
    );
    const client = new HoneyBookClient(MOCK_SESSION, 2578);
    const err = await client.request('GET', '/api/v2/users/uid_24').catch((e: unknown) => e);
    expect(err).not.toBeInstanceOf(EdgeBlockedError);
    expect((err as Error).message).toMatch(/auth expired.*use_magic_link/);
  });

  it('control: a genuine 429 still retries once, then reports rate limiting', async () => {
    vi.useFakeTimers();
    const fetchSpy = vi
      .spyOn(globalThis, 'fetch')
      .mockImplementation(async () => new Response('{"error":"too many requests"}', { status: 429 }));
    const client = new HoneyBookClient(MOCK_SESSION, 2578);
    const caught = client.request('GET', '/api/v2/users/uid_24').catch((e: unknown) => e);
    await vi.advanceTimersByTimeAsync(2000);
    const err = await caught;
    expect(err).not.toBeInstanceOf(EdgeBlockedError);
    expect((err as Error).message).toMatch(/Rate limited by HoneyBook API/);
    expect(fetchSpy).toHaveBeenCalledTimes(2);
  });
});
